[package]
name = "nix-rust-wasm-example"
version = "0.0.1"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = 'abort'

[features]
default = [ "wee_alloc" ]
wee_alloc = [ "dep:wee_alloc" ]

[dependencies]
wee_alloc = { version = "0.4.5", optional = true }
